In [4]:
faqs = """
Marwadi University (MU)[1] is a private university[2] located in Rajkot, Gujarat, India. It was established on 9 May 2016 by the Marwadi Education Foundation through The Gujarat Private Universities (Amendment) Act, 2016.[3] As of 2017, it offers 54 different courses.[4] It is graded A+ by NAAC.[5]

The university operates under the division of Marwadi Education Foundation's Group of Institutions (MEFGI). MEFGI commenced its operations in the year 2008. It was established as a primary unit of Marwadi Education Foundation under the Bombay Public Trust Act 1950. Marwadi University is aided by the Marwadi Shares and Finance Limited, a stock broking company in India and Chandarana Intermediaries Brokers Pvt. Ltd. (CIBPL), a firm dealing in technical and arbitrage trading.[6]

Campus
The campus is located on 52 acres of land, having a distance of nearly 40 minutes from railway and airports. The university comprises eight multi-storey buildings.[7] Laboratories, research facilities, student clubs, sports club and college cafeteria are available.[8]

There are two libraries with RFID technologies, 60+ computer systems, 50000+ books.[9] The campus also includes banking and ATM facilities.[10] Around 70+ buses function every day at regular intervals for students and staff.[11] There are hostel rooms with internet facilities, laundry, dance rooms, libraries etc. and capacity to occupy over 2000 students.[12]

Controversies
Marwadi University has been involved in several controversies:

Ragging Incident (October 2022)
In October 2022, a 19-year-old BBA student alleged that he was sodomized by five fellow students in the university hostel. The accused reportedly filmed a video of the victim bathing and used it to blackmail him, pressuring him to harm himself. The university took immediate action by involving the anti-ragging committee and initiating the process to expel the accused students.[13][14]

Hostel Video Scandal
An engineering student from Andhra Pradesh was secretly filmed by her roommate while bathing, and the video was circulated among others. This incident raised concerns about student safety and privacy within the university's hostels.[15]

Marijuana Cultivation on Campus
Authorities discovered marijuana plants being cultivated near the boys' hostel within the university campus. This incident brought the university under scrutiny regarding campus security and regulatory enforcement.[16][17]

Physical Altercation
A physical altercation between two female students was caught on video and widely shared online. The incident sparked discussions about student behavior and discipline on campus.[18]

Academics
Academic programmes
Marwadi University provides Undergraduate, Postgraduate, Diploma and Doctoral degrees. The university offers all these degrees in different faculties like Engineering, Science, Management, Computer Applications, Commerce, Law, Pharmacy, Agriculture and Physiotherapy.[19]

Ranking
Faculty of Law, Marwadi University, has been listed as one of the top law schools in India in Forbes India's Legal Powerlist 2020.[20]

Param Shavak
For enhancement of educational infrastructure of the country, Marwadi University has been granted with supercomputer 'Param Shavak' by Gujarat Council on Science and Technology (GUJCOST), Gujarat Government. Param Shavak supercomputing system will aid high-end computations and research work in AI, CE/IT, ICT, ML fields.[21]

Organisation and administration
Faculties
Faculty of Engineering
The faculty offers undergraduate, postgraduate, and diploma degrees.

The undergraduate programmes offered are Bachelors in Computer Engineering, Information Technology, Electrical Engineering, Automobile Engineering, Chemical Engineering, Civil Engineering, Mechanical Engineering, Computer Engineering (Big Data & Analytics), Information and Communication Technology, and Computer Engineering (Artificial Intelligence).[22]

The postgraduate programmes offered are Masters in Chemical Engineering, Cyber Security, Environmental Engineering, Computer Engineering, Geotechnical Engineering, Electric Vehicle, CAD/CAM Engineering, Communication System Engineering, Structural Engineering, Thermal Engineering, Transportation Engineering and VLSI.[23]

The diploma courses offered are Diploma in Computer Engineering, Mechanical Engineering, Chemical Engineering, Electrical Engineering, Civil Engineering, Automobile Engineering and Information and Communication Technology.[24]

Faculty of Science
The faculty offers undergraduate and postgraduate degrees.

The undergraduate programmes offered are Bachelor of Science (B.Sc.) in Chemistry, Microbiology, Physics, Mathematics and Agriculture.[25]

The postgraduate programmes offered are in Master of Science (M.Sc.) in Chemistry Microbiology, Mathematics, Bio-Technology, Physics and Environmental Science.[26]

Faculty of Architecture (Discontinued)
The faculty provides Bachelor of Architecture, a 5-year undergraduate programme, which focuses on educating students to develop innovative ideas and skills in the architectural discipline.[27]

Faculty of Management Studies
The faculty offers undergraduate and postgraduate degrees in business management.

The undergraduate programmes offered are Bachelor of Business Administration, Bachelor of Business Administration (Honors) and Bachelor of Business Administration (Financial Markets).[28]

The postgraduate programmes offered are Master of Business Administration, Master of Business Administration in Business Analytics and Master of Business Administration in Executive Program.[29]

Faculty of Computer Applications
The undergraduate programme offered is Bachelor of Computer Applications.[30] The postgraduate programme offered is Master of Computer Application.[31]

Faculty of Commerce
The faculty offers undergraduate programmes in Bachelor of Commerce and Bachelor of Commerce (Honors).[32]

Faculty of Law
The faculty of law offers undergraduate degrees and postgraduate degrees. The undergraduate programmes offered are BA LLB and B.Com. LLB.[33] The postgraduate programme offered is LLM.[34]

Faculty of Pharmacy
The faculty offers a 4-year undergraduate program, Bachelor of Pharmacy and two years Masters of Pharmacy, which trains students with in-depth knowledge in pharmaceutical sciences.[35]

Faculty of Physiotherapy
The faculty offers a 3-year undergraduate programme, Bachelor of Physiotherapy.[36]

Faculty of Computer Science
The faculty offers a postgraduate programme in Master of Computer Science in Cyber Security & law.[37]

Centre
Entrepreneurship Development Cell
The university aims to offer youth help to set up their own businesses. To aid this initiative, Marwadi University has developed the Entrepreneurship Development Cell, which has implemented various university-based policies on the campus, such as: - Student Startup and Innovation Policy of Government of Gujarat - New Generation Innovation And Entrepreneurship Development Centre (NewGen-IEDC) The cell provides support services to set up businesses by providing them pre-incubation support, guidance for the subsidy, preparation of project reports, registrations, management consultancy and more.[38]

Intellectual Property Rights Cell
To create awareness about intellectual property rights, the university conducts various workshops, seminars, and training courses on IPR.[39]

Innovation and Incubation Research (MUIIR) Center
Marwadi University Innovation and Incubation Research (MUIIR) Centre inks strategic MOUs to assist entrepreneurs who are focused on Energy Conservation, AI and Big Data analytics, Sustainable Development and Industry 4.0. 32+ start-ups from engineering, Paramedical, Management and Science are well-supported, and the amount of 50 lakhs + has been raised with the help of MUIIR.[40]

Student life
Clubs
Students clubs at Marwadi University include Aero modeling and Robotics Club, Fitness Club, Team-building Club, Green Club, Computer-Aided Manufacturing Club, Cultural Club, Marketing Club, Finance Club, HR Club, Music Club etc.[41]
"""

In [5]:
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
tokenizer = Tokenizer()

In [7]:
tokenizer.fit_on_texts([faqs])

In [8]:
len(tokenizer.word_index)

476

In [9]:
input_sequence =[]
for sentence in faqs.split('\n'):
    tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
    # print(tokenized_sentence) # Commenting out this print statement as it's not needed

    for i in range(1,len(tokenized_sentence)):
        n_gram_sequence = tokenized_sentence[:i+1]
        input_sequence.append(n_gram_sequence) # Append the n_gram_sequence to input_sequence

In [10]:
#finding max len of the senctence
max_length = max([len(x) for x in input_sequence])


In [11]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
#add padding pre as all word are dependent
padded_input_sequence = pad_sequences(input_sequence,maxlen=max_length,padding='pre')

In [12]:
print(padded_input_sequence)

[[  0   0   0 ...   0   9   6]
 [  0   0   0 ...   9   6 149]
 [  0   0   0 ...   6 149 150]
 ...
 [  0   0   0 ...  13 475  13]
 [  0   0   0 ... 475  13  96]
 [  0   0   0 ...  13  96 476]]


In [13]:
X = padded_input_sequence[:,:-1]

In [14]:
y = padded_input_sequence[:,-1]

In [15]:
X  #making it as input

array([[  0,   0,   0, ...,   0,   0,   9],
       [  0,   0,   0, ...,   0,   9,   6],
       [  0,   0,   0, ...,   9,   6, 149],
       ...,
       [  0,   0,   0, ..., 474,  13, 475],
       [  0,   0,   0, ...,  13, 475,  13],
       [  0,   0,   0, ..., 475,  13,  96]], dtype=int32)

In [16]:
y   #making it as output

array([  6, 149, 150, ...,  13,  96, 476], dtype=int32)

In [17]:
X.shape

(1051, 83)

In [18]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes = 1051)

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense

In [20]:
model = Sequential()
model.add(Embedding(1051, output_dim=100, input_length=max_length-1))
model.add(LSTM(150))
model.add(Dense(1051,activation='softmax'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [21]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y, verbose=1, epochs=100 )


Epoch 1/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 7s 217ms/step - accuracy: 0.0625 - loss: 5.3473
Epoch 2/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 10s 208ms/step - accuracy: 0.0555 - loss: 5.1935
Epoch 3/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 5s 160ms/step - accuracy: 0.0832 - loss: 5.0129
Epoch 4/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 12s 216ms/step - accuracy: 0.0807 - loss: 4.9701
Epoch 5/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 10s 214ms/step - accuracy: 0.1256 - loss: 4.7520
Epoch 6/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 6s 173ms/step - accuracy: 0.1260 - loss: 4.5855
Epoch 7/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 7s 222ms/step - accuracy: 0.1273 - loss: 4.4852
Epoch 8/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 6s 179ms/step - accuracy: 0.1597 - loss: 4.3300
Epoch 9/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 11s 194ms/step - accuracy: 0.1932 - loss: 4.1061
Epoch 10/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 5s 162ms/step - accuracy: 0.2025 - loss: 4.0672
Epoch 11/100
33/33 ━━━━━━━━━━━━━━━━━━━━ 11s 172ms/step - accuracy: 0.2245 - loss: 3.8315
Epoch 12/100
33/33 ━━━━━━━━━━━━━━━━━

In [ ]:
def generate_text(seed_text, next_words, model, max_length, tokenizer):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_length-1, padding='pre')
        predicted_probabilities = model.predict(token_list, verbose=0)
        predicted_word_index = np.argmax(predicted_probabilities)
        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted_word_index:
                output_word = word
                break
        seed_text += " " + output_word
    return seed_text

# Example usage:
seed_text = "Marwadi University"
generated_text = generate_text(seed_text, 10, model, max_length, tokenizer)
print(generated_text)